# This compose file is for only this app in development mode
version: '2'

services:
  database:
    image: 'postgres:9.6'
    env_file:
      - 'dev.env'
    expose:
      - '5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass p4ssw0rd
    expose:
      - '6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  app:
    depends_on:
      - 'database'
      - 'redis'
    build: .
    ports:
      - '4000:9000'
    volumes:
      - '.:/tbclient'
    env_file:
      - 'dev.env'

volumes:
  redis:
  postgres:
